version: "3"

services:

  pgsql:
    image: postgres:13.3
    volumes:
      - ${PWD}/docker/provisions/postgres/startup:/docker-entrypoint-initdb.d/
      - ${PWD}/docker/provisions/postgres/conf:/etc/postgresql/
      - ${PWD}/docker/provisions/postgres/certs:/var/lib/postgresql/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  mongo:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  dbi-repositories:
    image: timniven/dbi-repositories:latest
    depends_on:
      - pgsql
      - mongo
    volumes:
      - ${PWD}:/dbi-repositories
    working_dir: /dbi-repositories
    environment:
      - PGSQL_HOST=pgsql
      - PGSQL_PORT=5432
      - PGSQL_USERNAME=test
      - PGSQL_PASSWORD=test
      - PGSQL_DB_NAME=test
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=password
    command: python -m unittest discover

networks:
  default:
    name: localdev
